[package]
name = "precompress"
version = "0.2.7"
description = "Precompress a directory of assets"
authors = ["Ryan Fowler <ryan.fowler19@gmail.com>"]
repository = "https://github.com/ryanfowler/precompress"
categories = ["command-line-utilities"]
keywords = ["compress", "assets", "brotli", "deflate", "gzip"]
license = "MIT"
edition = "2021"

[[bin]]
name = "precompress"
path = "src/main.rs"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
strip = true

[dependencies]
anyhow = { version = "1.0.71" }
brotli = { version = "3.3.4" }
clap = { version = "4.3.4", features = ["derive"] }
crossbeam = { version = "0.8.1" }
flate2 = { version = "1.0.26" }
ignore = { version = "0.4.20" }
num_cpus = { version = "1.15.0" }
phf = { version = "0.11.1", features = ["macros"] }
strum = { version = "0.24.1" }
strum_macros = { version = "0.25.0" }
zstd = { version = "0.12.3" }

[target.'cfg(not(target_os = "windows"))'.dependencies]
jemallocator = { version = "0.5.0" }
