[package]
name = "precompress"
version = "0.2.2"
description = "Precompress a directory of assets"
authors = ["Ryan Fowler <ryan.fowler19@gmail.com>"]
repository = "https://github.com/ryanfowler/precompress"
categories = ["command-line-utilities"]
keywords = ["compress", "assets", "brotli", "deflate", "gzip"]
license = "MIT"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "precompress"

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3
strip = "debuginfo"

[dependencies]
anyhow = { version = "1.0.69" }
brotli = { version = "3.3.4" }
clap = { version = "4.1", features = ["derive"] }
crossbeam = { version = "0.8.1" }
flate2 = { version = "1.0.25" }
ignore = { version = "0.4.20" }
jemallocator = { version = "0.5.0" }
num_cpus = { version = "1.15" }
phf = { version = "0.11.1", features = ["macros"] }
strum = { version = "0.24.1" }
strum_macros = { version = "0.24.3" }
zstd = { version = "0.12.3" }
