[package]
name = "precompress"
version = "0.2.9"
description = "Precompress a directory of assets"
authors = ["Ryan Fowler <ryan.fowler19@gmail.com>"]
repository = "https://github.com/ryanfowler/precompress"
categories = ["command-line-utilities"]
keywords = ["compress", "assets", "brotli", "deflate", "gzip"]
license = "MIT"
edition = "2021"

[[bin]]
name = "precompress"
path = "src/main.rs"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
strip = true

[dependencies]
anyhow = { version = "1.0.80" }
brotli = { version = "3.4.0" }
clap = { version = "4.5.2", features = ["derive"] }
crossbeam = { version = "0.8.4" }
flate2 = { version = "1.0.28" }
ignore = { version = "0.4.22" }
num_cpus = { version = "1.16.0" }
phf = { version = "0.11.2", features = ["macros"] }
strum = { version = "0.26.1" }
strum_macros = { version = "0.26.2" }
zstd = { version = "0.13.0" }

[target.'cfg(not(target_os = "windows"))'.dependencies]
jemallocator = { version = "0.5.4" }
