
name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.65.0
        default: true
        components: clippy, rustfmt

    - name: Run cargo build
      run: cargo build

    - name: Run cargo test
      run: cargo test

    - name: Run cargo clippy
      run: cargo clippy -- -D warnings
